pipeline:
  build:
    when:
      event: push
      branch: master
    image: starefossen/ruby-node:2-8
    commands:
      - npm install --silent
      - bundle install --binstubs
      - npm run publish

  publish:
    when:
      event: push
      branch: master
    image: plugins/gh-pages
    secrets: [ github_username, github_password ]