# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'https://rubygems.org'

gem "middleman", "~>3.1.5"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

# Styleguide shebang
gem "kss"

# uStyle
gem 'ustyle', :git => "git@github.com:uswitch/ustyle.git", :branch => "new-grid"

gem "aws-s3"
gem "capistrano", "2.15.5"

# Cross-templating language block fix for Ruby 1.8
platforms :mri_18 do
  gem "ruby18_source_location"
end